name: Lint and Test Charts

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.1.0
        with:
          version: "v0.9.0"
        # Only build a kind cluster if there are chart changes to test.
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install MetalLB to allow LoadBalancer services
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl create ns metallb-system
          kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.9.3/manifests/metallb.yaml
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: config
            namespace: metallb-system
          data:
            config: |
              address-pools:
              - name: default
                protocol: layer2
                addresses:
                - 172.17.255.1-172.17.255.200
          EOF

      - name: Run chart-testing (install)
        run: ct install --config config.yaml --helm-extra-args "--set image.tag=sha-$(echo ${GITHUB_SHA} | cut -c1-8)"
